/* Guards the enum value sets the Entity State tab checks declaration text against. Pure ASCII.
 *
 * schema_slice.js was generated by scraping DOOM's localized inspector strings, whose ids read
 * #str_snapmaps_enum_<enumType>_<LABEL> and #str_snapmaps_enum_<enumType>_<LABEL>_desc. That
 * yields the label an editor widget displays, not the constant a declaration serializes, and it
 * yields each label twice -- once bare, once with the trailing underscore left over from _desc.
 * So snapPoiElement_t was listed as TYPE_ONE / TYPE_ONE_ / ... when the engine's own constants
 * are SNAP_POI_1 .. SNAP_POI_5, and a map that legitimately used SNAP_POI_2 was warned about.
 *
 * The sets below are the engine reflection constants. Two checks run: the corrected sets must
 * match exactly, and no enum anywhere in the file may carry the trailing-underscore twin that
 * identifies a label scrape, so a future regeneration cannot quietly reintroduce the pattern.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const SLICE = path.join(__dirname, '..', 'src', 'ui', 'webview', 'schema_slice.js');
const src = fs.readFileSync(SLICE, 'utf8').replace(/\r\n/g, '\n');
const schema = JSON.parse(src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1));

let failures = 0;
function check(ok, message) {
  if (!ok) { console.error('[FAIL] ' + message); failures++; }
}

const ENUMS_FROM_REFLECTION = {
  walkState_t: ['WALKSTATE_NOCLIP', 'WALKSTATE_WALKING', 'WALKSTATE_RUNNING', 'WALKSTATE_SPRINTING', 'WALKSTATE_MAX'],
  coopHazardDamage_t: ['COOP_HAZARD_DAMAGE_FIRE', 'COOP_HAZARD_DAMAGE_ELECTRICITY', 'COOP_HAZARD_DAMAGE_RADIATION', 'COOP_HAZARD_DAMAGE_POISON', 'COOP_HAZARD_DAMAGE_MAX'],
  snapSpawnEncounterTarget_t: ['PLAYER', 'ACTIVATOR', 'ENCOUNTER'],
  snapSpawnEncounterLocation_t: ['IN_MODULE', 'IN_SURROUNDING_MODULE', 'AROUND_SPAWN_TARGET', 'EXPLICIT_LOCATION'],
  snapDropStyle_t: ['SNAP_DROP_REMOVE', 'SNAP_DROP_RESET', 'SNAP_DROP_TO_GROUND', 'SNAP_DROP_MAX'],
  playerLoadoutAbility_t: ['LOADOUT_ABILITY_LEDGE_GRAB', 'LOADOUT_ABILITY_DOUBLE_JUMP'],
  snapAISpawnBehavior_t: ['SNAP_AI_SPAWN_BEHAVIOR_DEFAULT', 'SNAP_AI_SPAWN_BEHAVIOR_AMBUSH', 'SNAP_AI_SPAWN_BEHAVIOR_HUNT', 'SNAP_AI_SPAWN_BEHAVIOR_DEFEND'],
  snapAmmoFilter_t: ['SNAP_AMMO_FILTER_ALL', 'SNAP_AMMO_FILTER_BFG', 'SNAP_AMMO_FILTER_BULLET', 'SNAP_AMMO_FILTER_CELL', 'SNAP_AMMO_FILTER_FUEL', 'SNAP_AMMO_FILTER_ROCKET', 'SNAP_AMMO_FILTER_SHELL'],
  snapUniversalAmmo_t: ['SNAP_AMMO_PACK', 'SNAP_AMMO_BOX', 'SNAP_AMMO_SINGLE', 'SNAP_AMMO_BFG', 'SNAP_AMMO_BULLET', 'SNAP_AMMO_CELL', 'SNAP_AMMO_FUEL', 'SNAP_AMMO_ROCKET', 'SNAP_AMMO_SHELL'],
  snapPoiElement_t: ['SNAP_POI_INVALID', 'SNAP_POI_1', 'SNAP_POI_2', 'SNAP_POI_3', 'SNAP_POI_4', 'SNAP_POI_5', 'SNAP_POI_MAX'],
  snapWinCondition_t: ['HIGHEST', 'LOWEST'],
  snapWinDataSource_t: ['PLAYER_SCORE', 'TEAM_SCORE', 'RESOURCE'],
  snapSpawnItemLocation_t: ['SNAP_SPAWN_ITEM_LOCATION_ACTIVATOR', 'SNAP_SPAWN_ITEM_LOCATION_EXPLICIT_LOCATION'],
  snapEndGameState_t: ['SNAP_END_GAME_VICTORY', 'SNAP_END_GAME_DRAW', 'SNAP_END_GAME_DEFEAT', 'SNAP_END_GAME_MAX'],
  snapVisibilityFilter_t: ['SNAP_VISIBILITY_HIDDEN', 'SNAP_VISIBILITY_SHOWN', 'SNAP_VISIBILITY_ANY'],
  snapCauseOfDeath_t: ['CAUSE_OF_DEATH_ANY', 'CAUSE_OF_DEATH_NON_GLORYKILL', 'CAUSE_OF_DEATH_GLORYKILL']
};

check(schema.enums && typeof schema.enums === 'object', 'schema_slice.js carries no enums table');

Object.keys(ENUMS_FROM_REFLECTION).forEach(function (type) {
  const want = ENUMS_FROM_REFLECTION[type];
  const got = schema.enums[type];
  if (!got) { check(false, type + ' is missing from the enums table'); return; }
  check(got.join(',') === want.join(','),
    type + ' does not match the engine constants: expected [' + want.join(', ') + '] but found [' + got.join(', ') + ']');
});

/* The scrape signature: a member and that same member with a trailing underscore, which is what
 * the _desc string id leaves behind. One pair anywhere means the file was regenerated by the
 * broken path. */
Object.keys(schema.enums).forEach(function (type) {
  const members = schema.enums[type];
  const present = {};
  members.forEach(function (m) { present[m] = true; });
  members.forEach(function (m) {
    check(!present[m + '_'],
      type + ' carries both ' + m + ' and ' + m + '_, the trailing-underscore twin left by a _desc string id');
  });
});

/* SNAP_POI_2 is the value in the report that started this: it must validate. TYPE_TWO is the
 * localized label that used to stand in for it: it must not. */
check(schema.enums.snapPoiElement_t.indexOf('SNAP_POI_2') !== -1,
  'SNAP_POI_2 is not accepted for snapPoiElement_t');
check(schema.enums.snapPoiElement_t.indexOf('TYPE_TWO') === -1,
  'the localized label TYPE_TWO is still accepted for snapPoiElement_t');

if (failures) { console.error(failures + ' check(s) failed'); process.exit(1); }
console.log('decl enum values: ok (' + Object.keys(ENUMS_FROM_REFLECTION).length + ' corrected sets, ' +
  Object.keys(schema.enums).length + ' enums scanned)');
