/* map_package_test.c -- the map-embedded override package consumer.
 *
 * The contract these tests pin is the one that keeps a stranger's map from
 * killing the process: shard scan + reassembly match the reference
 * implementation (every fixture here was GENERATED by src/map_package.py in
 * the dev repo -- see map_package_fixtures.h), unsafe archives never touch
 * the disk, and the load gate refuses -- never crashes -- when a declared
 * package is not in the boot snapshot. Consent runs synchronously through
 * the test seam; production raises the same decision on its own thread.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#include <stdio.h>
#include <string.h>

#include "map_package.h"
#include "map_package_fixtures.h"

/* The gate defers to runtime registration instead of demanding a restart, and a successful
 * install requests a re-arm. Neither is linked into this test; the runtime path is exercised
 * live, not here. */
int sh_decl_server_registration_succeeded(void)
{
    return 0;
}

void sh_decl_server_request_rearm(void)
{
}

static int g_failed;

#define CHECK(expr) do {                                                        \
    if (!(expr)) {                                                              \
        fprintf(stderr, "%s:%d: CHECK failed: %s\n", __FILE__, __LINE__, #expr); \
        g_failed++;                                                             \
    }                                                                           \
} while (0)

void backend_log(const char *message)
{
    (void)message;   /* the unit tests assert on returned state, not log text */
}

static void join(char *out, size_t size, const char *a, const char *b)
{
    _snprintf_s(out, size, _TRUNCATE, "%s\\%s", a, b);
}

static int make_dir(const char *path)
{
    return CreateDirectoryA(path, NULL) || GetLastError() == ERROR_ALREADY_EXISTS;
}

static int touch(const char *path, const char *body)
{
    HANDLE file = CreateFileA(path, GENERIC_WRITE, 0, NULL, CREATE_ALWAYS,
                              FILE_ATTRIBUTE_NORMAL, NULL);
    DWORD wrote = 0;
    if (file == INVALID_HANDLE_VALUE) return 0;
    if (body && body[0]) WriteFile(file, body, (DWORD)strlen(body), &wrote, NULL);
    CloseHandle(file);
    return 1;
}

static void remove_tree(const char *path)
{
    char pattern[MAX_PATH], child[MAX_PATH];
    WIN32_FIND_DATAA found;
    HANDLE search;
    _snprintf_s(pattern, sizeof(pattern), _TRUNCATE, "%s\\*", path);
    search = FindFirstFileA(pattern, &found);
    if (search != INVALID_HANDLE_VALUE) {
        do {
            if (strcmp(found.cFileName, ".") == 0 ||
                strcmp(found.cFileName, "..") == 0) continue;
            join(child, sizeof(child), path, found.cFileName);
            if (found.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) remove_tree(child);
            else DeleteFileA(child);
        } while (FindNextFileA(search, &found));
        FindClose(search);
    }
    RemoveDirectoryA(path);
}

static int file_exists(const char *path)
{
    DWORD attrs = GetFileAttributesA(path);
    return attrs != INVALID_FILE_ATTRIBUTES && !(attrs & FILE_ATTRIBUTE_DIRECTORY);
}

static int dir_exists(const char *path)
{
    DWORD attrs = GetFileAttributesA(path);
    return attrs != INVALID_FILE_ATTRIBUTES && (attrs & FILE_ATTRIBUTE_DIRECTORY);
}

/* Read a whole file; returns bytes read into caller's buffer, or -1. */
static long read_file(const char *path, unsigned char *buf, size_t cap)
{
    HANDLE h = CreateFileA(path, GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING,
                           FILE_ATTRIBUTE_NORMAL, NULL);
    DWORD rd = 0;
    if (h == INVALID_HANDLE_VALUE) return -1;
    if (!ReadFile(h, buf, (DWORD)cap, &rd, NULL)) { CloseHandle(h); return -1; }
    CloseHandle(h);
    return (long)rd;
}

/* Verify an unpacked tree matches the fixture package byte for byte. */
static void check_unpacked_members(const char *dest)
{
    size_t i;
    for (i = 0; i < sizeof(fix_members) / sizeof(fix_members[0]); i++) {
        char rel[MAX_PATH], path[MAX_PATH];
        unsigned char buf[4096];
        long got;
        size_t j;
        strcpy_s(rel, sizeof rel, fix_members[i].path);
        for (j = 0; rel[j]; j++) if (rel[j] == '/') rel[j] = '\\';
        join(path, sizeof path, dest, rel);
        got = read_file(path, buf, sizeof buf);
        CHECK(got == (long)fix_members[i].len);
        if (got == (long)fix_members[i].len && got > 0)
            CHECK(memcmp(buf, fix_members[i].body, (size_t)got) == 0);
    }
}

/* Is `json` structurally balanced outside string literals? Not a parser -- just enough to catch
 * the ways a bad splice breaks a document: an unclosed container, or a comma left with nothing
 * on one side of it. */
static int json_well_formed(const char *json, size_t len)
{
    size_t i;
    int depth = 0, in_string = 0;
    char prev = 0;
    for (i = 0; i < len; i++) {
        char c = json[i];
        if (in_string) {
            if (c == '\\') { i++; continue; }
            if (c == '"') in_string = 0;
            continue;
        }
        if (c == '"') { in_string = 1; prev = c; continue; }
        if (c == ' ' || c == '\t' || c == '\r' || c == '\n') continue;
        if (c == '{' || c == '[') depth++;
        if (c == '}' || c == ']') {
            if (prev == ',') return 0;          /* trailing comma before a close */
            depth--;
            if (depth < 0) return 0;
        }
        if (c == ',' && (prev == ',' || prev == '[' || prev == '{')) return 0;
        prev = c;
    }
    return depth == 0 && !in_string;
}

/* Strip `json` and assert the shape of the result. Frees the stripped buffer. */
static void check_strip(const char *json, size_t len, int expect_stripped)
{
    size_t out_len = 0;
    char *out = sh_mpkg_strip(json, len, &out_len);
    sh_mpkg_decl after[SH_MPKG_MAX_PACKAGES];

    if (!expect_stripped) {
        CHECK(out == NULL);
        if (out) HeapFree(GetProcessHeap(), 0, out);
        return;
    }

    CHECK(out != NULL);
    if (!out) return;
    CHECK(out_len > 0);
    CHECK(out_len < len);                      /* something actually came out */
    CHECK(strlen(out) == out_len);             /* NUL-terminated at the reported length */
    CHECK(json_well_formed(out, out_len));
    CHECK(sh_mpkg_scan(out, out_len, after, SH_MPKG_MAX_PACKAGES) == 0);   /* no shards left */
    HeapFree(GetProcessHeap(), 0, out);
}

int main(void)
{
    char temp[MAX_PATH], root[MAX_PATH], overrides[MAX_PATH], sub[MAX_PATH];
    DWORD pid = GetCurrentProcessId();
    char err[SH_MPKG_ERR_CAP];
    sh_mpkg_decl decls[SH_MPKG_MAX_PACKAGES];
    size_t n;

    GetTempPathA(sizeof(temp), temp);
    _snprintf_s(root, sizeof(root), _TRUNCATE, "%ssh_mpkg_test_%lu",
                temp, (unsigned long)pid);
    remove_tree(root);
    CHECK(make_dir(root));
    join(overrides, sizeof overrides, root, "overrides");
    CHECK(make_dir(overrides));

    /* ---- scan: the no-shard fast path ---------------------------------- */
    n = sh_mpkg_scan("{\"variables\":{\"string\":[]}}", 27, decls, SH_MPKG_MAX_PACKAGES);
    CHECK(n == 0);
    /* header-shaped PROSE (in a value, and in an entity name) is not a shard */
    n = sh_mpkg_scan(fix_map_prose, fix_map_prose_len, decls, SH_MPKG_MAX_PACKAGES);
    CHECK(n == 0);

    /* ---- scan: the happy map, compact and pretty ----------------------- */
    n = sh_mpkg_scan(fix_map_happy, fix_map_happy_len, decls, SH_MPKG_MAX_PACKAGES);
    CHECK(n == 1);
    CHECK(strcmp(decls[0].id, FIX_PKG_ID) == 0);
    CHECK(strcmp(decls[0].digest, FIX_DIGEST) == 0);
    CHECK(decls[0].total == FIX_SHARDS);
    CHECK(decls[0].present == FIX_SHARDS);
    CHECK(decls[0].consistent == 1 && decls[0].complete == 1);

    n = sh_mpkg_scan(fix_map_happy_pretty, fix_map_happy_pretty_len, decls,
                     SH_MPKG_MAX_PACKAGES);
    CHECK(n == 1);
    CHECK(decls[0].complete == 1);

    /* ---- scan: the broken variants ------------------------------------- */
    n = sh_mpkg_scan(fix_map_incomplete, fix_map_incomplete_len, decls,
                     SH_MPKG_MAX_PACKAGES);
    CHECK(n == 1 && decls[0].present == FIX_SHARDS - 1 && decls[0].complete == 0);
    n = sh_mpkg_scan(fix_map_duplicate, fix_map_duplicate_len, decls,
                     SH_MPKG_MAX_PACKAGES);
    CHECK(n == 1 && decls[0].consistent == 0 && decls[0].complete == 0);
    n = sh_mpkg_scan(fix_map_inconsistent, fix_map_inconsistent_len, decls,
                     SH_MPKG_MAX_PACKAGES);
    CHECK(n == 1 && decls[0].consistent == 0);

    /* ---- extract: happy ------------------------------------------------- */
    {
        size_t out_len = 0;
        unsigned char *payload = sh_mpkg_extract(fix_map_happy, fix_map_happy_len,
                                                 FIX_PKG_ID, &out_len, err, sizeof err);
        CHECK(payload != NULL);
        CHECK(out_len == fix_payload_len);
        if (payload && out_len == fix_payload_len)
            CHECK(memcmp(payload, fix_payload, out_len) == 0);
        if (payload) HeapFree(GetProcessHeap(), 0, payload);

        payload = sh_mpkg_extract(fix_map_happy_pretty, fix_map_happy_pretty_len,
                                  FIX_PKG_ID, &out_len, err, sizeof err);
        CHECK(payload != NULL && out_len == fix_payload_len);
        if (payload && out_len == fix_payload_len)
            CHECK(memcmp(payload, fix_payload, out_len) == 0);
        if (payload) HeapFree(GetProcessHeap(), 0, payload);
    }

    /* ---- extract: every reference-error case --------------------------- */
    {
        size_t out_len = 0;
        CHECK(sh_mpkg_extract(fix_map_incomplete, fix_map_incomplete_len, FIX_PKG_ID,
                              &out_len, err, sizeof err) == NULL);
        CHECK(strstr(err, "incomplete") != NULL);
        CHECK(sh_mpkg_extract(fix_map_duplicate, fix_map_duplicate_len, FIX_PKG_ID,
                              &out_len, err, sizeof err) == NULL);
        CHECK(strstr(err, "duplicate") != NULL);
        CHECK(sh_mpkg_extract(fix_map_inconsistent, fix_map_inconsistent_len, FIX_PKG_ID,
                              &out_len, err, sizeof err) == NULL);
        CHECK(strstr(err, "inconsistent") != NULL);
        CHECK(sh_mpkg_extract(fix_map_wrongdigest, fix_map_wrongdigest_len, FIX_PKG_ID,
                              &out_len, err, sizeof err) == NULL);
        CHECK(strstr(err, "failed its digest") != NULL);
        CHECK(sh_mpkg_extract(fix_map_corrupt, fix_map_corrupt_len, FIX_PKG_ID,
                              &out_len, err, sizeof err) == NULL);
        CHECK(strstr(err, "failed its digest") != NULL);
        CHECK(sh_mpkg_extract(fix_map_happy, fix_map_happy_len, "nope",
                              &out_len, err, sizeof err) == NULL);
        CHECK(strstr(err, "not present") != NULL);
    }

    /* ---- unpack: happy --------------------------------------------------- */
    {
        unsigned files = 0;
        join(sub, sizeof sub, root, "unpack");
        CHECK(sh_mpkg_unpack(fix_payload, fix_payload_len, sub, &files, err, sizeof err) == 1);
        CHECK(files == FIX_FILE_COUNT);
        check_unpacked_members(sub);
    }

    /* ---- unpack: unsafe member paths refuse BEFORE anything is written -- */
    {
        unsigned files = 0;
        char escaped[MAX_PATH];
        join(sub, sizeof sub, root, "trav");
        CHECK(sh_mpkg_unpack(fix_payload_traversal, fix_payload_traversal_len, sub,
                             &files, err, sizeof err) == 0);
        CHECK(strstr(err, "unsafe member path") != NULL);
        CHECK(!dir_exists(sub));                       /* nothing was created */
        join(escaped, sizeof escaped, root, "evil.txt");
        CHECK(!file_exists(escaped));                  /* and nothing escaped */

        join(sub, sizeof sub, root, "abs");
        CHECK(sh_mpkg_unpack(fix_payload_absolute, fix_payload_absolute_len, sub,
                             &files, err, sizeof err) == 0);
        CHECK(strstr(err, "unsafe member path") != NULL);
        CHECK(!dir_exists(sub));
    }

    /* ---- gate: refuses when the boot snapshot is missing ----------------- */
    sh_mpkg_test_reset();
    CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 0);
    CHECK(strstr(sh_mpkg_test_last_refusal(), "snapshot") != NULL);

    /* ---- gate: no-shard maps pass without a snapshot too ----------------- */
    CHECK(sh_mpkg_gate("{\"variables\":{\"string\":[]}}", 27) == 1);
    CHECK(sh_mpkg_gate(fix_map_prose, fix_map_prose_len) == 1);

    /* ---- gate: missing package + user DECLINES --------------------------- */
    sh_mpkg_test_reset();
    sh_mpkg_test_set_consent_mode(SH_MPKG_CONSENT_DECLINE);
    sh_mpkg_boot_capture(root);
    CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 0);
    CHECK(sh_mpkg_test_session_installed_count() == 0);
    join(sub, sizeof sub, overrides, FIX_PKG_ID);
    CHECK(!dir_exists(sub));                           /* declined = not installed */
    CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 0);   /* still refused, no re-ask */

    /* ---- gate: missing package + user ACCEPTS -> installed, restart gated */
    sh_mpkg_test_reset();
    sh_mpkg_test_set_consent_mode(SH_MPKG_CONSENT_ACCEPT);
    sh_mpkg_boot_capture(root);
    CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 0);   /* THIS load still refused */
    CHECK(sh_mpkg_test_session_installed_count() == 1);
    join(sub, sizeof sub, overrides, FIX_PKG_ID);
    CHECK(dir_exists(sub));
    check_unpacked_members(sub);
    {
        char marker[MAX_PATH];
        unsigned char digest_buf[SH_MPKG_DIGEST_CHARS + 4];
        join(marker, sizeof marker, sub, "package.json");
        CHECK(file_exists(marker));
        join(marker, sizeof marker, sub, "smpkg.digest");
        CHECK(read_file(marker, digest_buf, sizeof digest_buf) == SH_MPKG_DIGEST_CHARS);
        CHECK(memcmp(digest_buf, FIX_DIGEST, SH_MPKG_DIGEST_CHARS) == 0);
    }
    /* The same map again. The package is installed but its identities are not registered YET:
     * this build asks the decl server to re-arm on the engine tick instead of demanding a
     * relaunch, and this test stubs sh_decl_server_registration_succeeded() to 0 -- i.e. the
     * re-arm has not finished. So the load is still refused, but the reason is now "still
     * registering", not "restart DOOM". The restart wording was the OLD contract. */
    CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 0);
    CHECK(strstr(sh_mpkg_test_last_refusal(), "still registering") != NULL);
    CHECK(strstr(sh_mpkg_test_last_refusal(), "restart") == NULL);

    /* ---- gate: once the package is in the captured set, the map passes ---- */
    sh_mpkg_test_reset();
    sh_mpkg_boot_capture(root);   /* the package is on disk now: this is the reboot */
    CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 1);
    /* control in the same state: a different-version map still refuses */
    sh_mpkg_test_set_consent_mode(SH_MPKG_CONSENT_DECLINE);
    CHECK(sh_mpkg_gate(fix_map_wrongdigest, fix_map_wrongdigest_len) == 0);

    /* ---- gate: name-grandfathered install (no digest sidecar) ------------ */
    {
        char root2[MAX_PATH], ov2[MAX_PATH], pkg2[MAX_PATH], marker2[MAX_PATH];
        _snprintf_s(root2, sizeof root2, _TRUNCATE, "%ssh_mpkg_test2_%lu",
                    temp, (unsigned long)pid);
        remove_tree(root2);
        CHECK(make_dir(root2));
        join(ov2, sizeof ov2, root2, "overrides");
        CHECK(make_dir(ov2));
        join(pkg2, sizeof pkg2, ov2, "testpkg");   /* map declares demons-testpkg */
        CHECK(make_dir(pkg2));
        join(marker2, sizeof marker2, pkg2, "package.json");
        CHECK(touch(marker2, "{}"));
        sh_mpkg_test_reset();
        sh_mpkg_boot_capture(root2);
        CHECK(sh_mpkg_gate(fix_map_happy, fix_map_happy_len) == 1);
        remove_tree(root2);
    }

    /* ---- gate: a hostile payload refuses the load AND never installs ----- */
    {
        char root3[MAX_PATH], ov3[MAX_PATH], evil3[MAX_PATH];
        _snprintf_s(root3, sizeof root3, _TRUNCATE, "%ssh_mpkg_test3_%lu",
                    temp, (unsigned long)pid);
        remove_tree(root3);
        CHECK(make_dir(root3));
        join(ov3, sizeof ov3, root3, "overrides");
        CHECK(make_dir(ov3));
        sh_mpkg_test_reset();
        sh_mpkg_test_set_consent_mode(SH_MPKG_CONSENT_ACCEPT);   /* even consenting... */
        sh_mpkg_boot_capture(root3);
        CHECK(sh_mpkg_gate(fix_map_evil, fix_map_evil_len) == 0);   /* refused, no crash */
        CHECK(sh_mpkg_test_session_installed_count() == 0);         /* ...installs nothing */
        join(evil3, sizeof evil3, ov3, "evil-pkg");
        CHECK(!dir_exists(evil3));
        remove_tree(root3);
    }

    /* ---- strip: the payload never reaches the engine ---------------------
     * An 8 KiB shard against the playtest's 4 KiB message budget is an idBitMsg overflow, so a
     * map that still carries its payload cannot be played -- installed package or not. The gate
     * reads the envelope; the engine must be handed the letter. */
    check_strip(fix_map_happy, fix_map_happy_len, 1);
    check_strip(fix_map_happy_pretty, fix_map_happy_pretty_len, 1);

    /* A broken payload strips too: the shards are unusable either way, and leaving them in is
     * exactly what makes the map unplayable. */
    check_strip(fix_map_incomplete, fix_map_incomplete_len, 1);
    check_strip(fix_map_duplicate, fix_map_duplicate_len, 1);
    check_strip(fix_map_wrongdigest, fix_map_wrongdigest_len, 1);

    /* No payload, no rewrite -- NULL means "use the original buffer", and an ordinary map must
     * never be copied, let alone edited, by this feature. */
    check_strip("{\"variables\":{\"string\":[]}}", 27, 0);
    check_strip(fix_map_prose, fix_map_prose_len, 0);   /* prose is an author's words, not ours */

    remove_tree(root);

    if (g_failed) {
        fprintf(stderr, "%d check(s) FAILED\n", g_failed);
        return 1;
    }
    printf("map_package_test: all checks passed\n");
    return 0;
}
