/* engine_globals.h -- resolve DOOM's DATA globals without hardcoding a build's RVAs.
 *
 * The signature layer already makes every engine FUNCTION portable: we scan for the function's
 * bytes, so it can sit anywhere. Data globals had no equivalent, so the backend carried raw
 * `module_base + 0x3056748`-style constants. Those are facts about one link output. DOOM 2016
 * ships two executables built from one source tree, and between them the data globals move by
 * roughly +0xE00000 to +0x1000000 -- nowhere near the code shift -- so a baked data RVA is the
 * one thing that could never survive the port.
 *
 * The fix is the trick the backend already used ad hoc in four places (sh_decode_rip_slot,
 * decode_table_global, decode_vtable_global, sp_decode_rip_any), generalised into a table: sign
 * the CODE SITE that computes the address, then read the RIP-relative displacement out of it.
 * The code site is findable by signature on any build; the displacement tells us where the global
 * lives on THIS build. Nothing is assumed about where either one is.
 *
 * Every entry is generated by the project's derivation tooling, never hand-written, and each is
 * accepted only when its anchor matches exactly once on BOTH shipped images.
 */
#ifndef BACKEND_ENGINE_GLOBALS_H
#define BACKEND_ENGINE_GLOBALS_H

#include <windows.h>
#include <stdint.h>
#include <stddef.h>

/* HOW `disp_slot` AND `disp_tail` ARE USED, and why both are needed:
 *
 * x86-64 measures a RIP-relative displacement from the end of the WHOLE INSTRUCTION, not from the
 * end of the displacement field. Those coincide only when nothing follows the displacement. An
 * instruction like `cmp dword ptr [rip+disp], 0` carries a 1-byte immediate AFTER the displacement,
 * so decoding it as `slot + 4 + disp` lands one byte short -- silently, on a plausible address, with
 * no symptom until something reads or writes through it.
 *
 * `disp_tail` is the number of immediate bytes that follow the displacement in the anchor
 * instruction (0 for the common `lea`/`mov` forms). The generator measures it; it is never guessed.
 * Getting this wrong is not a crash, it is a wrong answer, which is why it is a field rather than an
 * assumption. Do not hand-write an entry; regenerate. */
typedef struct global_entry {
    const char *name;        /* stable key, e.g. "editor_singleton" */
    const char *anchor;      /* masked byte pattern of the code site that computes the address */
    uint16_t    disp_slot;   /* byte offset of the RIP-relative disp32 within `anchor`; see above */
    uint8_t     disp_tail;   /* immediate bytes following that disp32 in the anchor instruction */
    int32_t     delta;       /* added to the decoded address; for adjacent-slot globals */
    uint32_t    pinned_rva;  /* the global's RVA on the pinned Vulkan build -- audit only, never used */
} global_entry;

typedef enum glb_status {
    GLB_OK = 0,
    GLB_ANCHOR_NOT_FOUND,   /* the code site did not match -- unknown build, or it was inline-hooked */
    GLB_ANCHOR_AMBIGUOUS,   /* matched more than once: not an identity, refuse rather than guess */
    GLB_UNKNOWN_NAME,
    GLB_OUT_OF_RANGE,       /* decoded address is outside the host image -- a bad decode, not a global */
    GLB_UNREADABLE          /* faulted reading the displacement */
} glb_status;

/* Resolve one named global against the live host image. Returns the address, or 0 on any failure
 * (never a guess, never a fallback to `pinned_rva`). Results are cached after the first success.
 * `out_status` may be NULL. */
uintptr_t glb_resolve(const uint8_t *module_base, const char *name, glb_status *out_status);

/* The generated table, NULL-terminated (final entry has name == NULL). */
extern const global_entry BACKEND_ENGINE_GLOBALS[];

size_t glb_db_count(void);

/* Resolve everything and log one line per entry. Returns the number that resolved. Call once at
 * install so a build we cannot serve is visible in the log rather than discovered field by field. */
size_t glb_resolve_all(const uint8_t *module_base);

#endif /* BACKEND_ENGINE_GLOBALS_H */
